---
language: node_js
node_js:
<<<<<<< HEAD
  - "stable"
=======
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
<<<<<<< HEAD
  - "4"
>>>>>>> de89ee7... message
=======
  - "6"
>>>>>>> c8dbedf... message

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
<<<<<<< HEAD
  - EMBER_TRY_SCENARIO=ember-lts-2.4
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
=======
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs linting and tests with current locked deps

    - stage: "Tests"
      name: "Tests"
      script:
        - npm run lint:hbs
        - npm run lint:js
        - npm test

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
<<<<<<< HEAD
    - EMBER_TRY_SCENARIO=ember-lts-2.12
    - EMBER_TRY_SCENARIO=ember-lts-2.16
    - EMBER_TRY_SCENARIO=ember-lts-2.18
    - EMBER_TRY_SCENARIO=ember-release
    - EMBER_TRY_SCENARIO=ember-beta
    - EMBER_TRY_SCENARIO=ember-canary
    - EMBER_TRY_SCENARIO=ember-default
>>>>>>> de89ee7... message

matrix:
  fast_finish: true
  allow_failures:
=======
    - stage: "Additional Tests"
      env: EMBER_TRY_SCENARIO=ember-lts-2.16
    - env: EMBER_TRY_SCENARIO=ember-lts-2.18
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
>>>>>>> c8dbedf... message
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery

before_install:
  - npm config set spin false
  - npm install -g npm@4
  - npm --version

script:
<<<<<<< HEAD
<<<<<<< HEAD
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
=======
  - npm run lint:js
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
>>>>>>> de89ee7... message
=======
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
>>>>>>> c8dbedf... message
